services:
  windows-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    command: pwsh -File ./install/windows/run_unit_test.ps1

  windows-test-shell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    command: pwsh
    stdin_open: true
    tty: true
