[tools]
act = "latest"
aws-sam-cli = "latest"
awscli = "latest"
chezmoi = "latest"
docker-compose = "latest"
gh = "latest"
go = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
shfmt = "latest"
uv = "latest"
